const Categories = Object.freeze({
    VENUE_LOCATION: "VENUE_LOCATION",
    CATERING_FOOD_SERVICES: "CATERING_FOOD_SERVICES",
    DECORATIONS_RENTALS: "DECORATIONS_RENTALS",
    ENTERTAINMENT_PERFORMERS: "ENTERTAINMENT_PERFORMERS",
    PHOTOGRAPHY_VIDEOGRAPHY: "PHOTOGRAPHY_VIDEOGRAPHY",
    EVENT_PLANNING_COORDINATION: "EVENT_PLANNING_COORDINATION",
    INVITATIONS_PRINTING: "INVITATIONS_PRINTING",
    TRANSPORTATION: "TRANSPORTATION",
    BEAUTY_FASHION: "BEAUTY_FASHION",
    SOUND_LIGHTING: "SOUND_LIGHTING",
    RELIGIOUS_CULTURAL: "RELIGIOUS_CULTURAL",
    GIFTS_FAVORS: "GIFTS_FAVORS"
});

module.exports = Categories