const Districts = Object.freeze({
    AMPARA: "AMPARA",
    ANURADHAPURA: "ANURADHAPURA",
    BADULLA: "BADULLA",
    BATTICALOA: "BATTICALOA",
    COLOMBO: "COLOMBO",
    GALLE: "GALLE",
    GAMPAHA: "GAMPAHA",
    HAMBANTOTA: "HAMBANTOTA",
    JAFFNA: "JAFFNA",
    KALUTARA: "KALUTARA",
    KANDY: "KANDY",
    KEGALLE: "KEGALLE",
    KILINOCHCHI: "KILINOCHCHI",
    KURUNEGALA: "KURUNEGALA",
    MANNAR: "MANNAR",
    MATALE: "MATALE",
    MATARA: "MATARA",
    MONARAGALA: "MONARAGALA",
    MULLAITIVU: "MULLAITIVU",
    NUWARA_ELIYA: "NUWARA_ELIYA",
    POLONNARUWA: "POLONNARUWA",
    PUTTALAM: "PUTTALAM",
    RATNAPURA: "RATNAPURA",
    TRINCOMALEE: "TRINCOMALEE",
    VAVUNIYA: "VAVUNIYA"
});

module.exports = Districts